[package]
name = "numpy"
version = "0.4.1"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>", "Yuji Kanagawa <yuji.kngw.80s.revive@gmail.com>"]
description = "Rust binding of NumPy C-API"
documentation = "https://rust-numpy.github.io/rust-numpy/numpy"
repository = "https://github.com/rust-numpy/rust-numpy"
keywords = ["numpy", "python", "binding"]
license-file = "LICENSE"

[dependencies]
cfg-if = "0.1.6"
libc = "0.2.44"
num-complex = "0.2.1"
num-traits = "0.2.6"
ndarray = "0.12"
pyo3 = "0.5.4"

[features]
# In default setting, python version is automatically detected
default = []
# Use this feature when building python2 binding.
python2 = ["pyo3/python2"]
# Use this feature when building python3 binding.
python3 = ["pyo3/python3"]

